-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS blockchain_facts;

-- Use the blockchain_facts database
USE blockchain_facts;

-- Create the table to store blockchain facts
CREATE TABLE IF NOT EXISTS facts (
    fact_id INT PRIMARY KEY,
    fact_text TEXT
);

-- Insert facts into the table
INSERT INTO facts (fact_id, fact_text) VALUES
    (1, 'Blockchain is a decentralized and distributed ledger technology.'),
    (2, 'Bitcoin, created in 2009, was the first cryptocurrency and blockchain implementation.'),
    (3, 'Ethereum introduced smart contracts, enabling programmable and self-executing agreements.'),
    (4, 'Web3 refers to the third generation of the internet that emphasizes decentralization, interoperability, and user control.'),
    (5, 'Decentralized applications (DApps) operate on a peer-to-peer network rather than relying on a centralized server.'),
    (6, 'Ethereum introduced the concept of smart contracts, enabling programmable and self-executing agreements on the blockchain'),
    (7, 'Altcoins are alternative cryptocurrencies to Bitcoin, such as Ethereum (ETH), Ripple (XRP), and Litecoin (LTC).'),
    (8, 'Solidity is a programming language designed for writing smart contracts on the Ethereum blockchain.'),
    (9, 'Smart contracts are self-executing contracts with the terms of the agreement directly written into code.'),
    (10, 'Blockchain development often involves languages like JavaScript, Python, and C++ for various tasks outside of smart contract development.'),
    (11, 'Consensus algorithms, like Proof of Work (PoW) and Proof of Stake (PoS), are crucial in blockchain networks for reaching agreement on the state of the blockchain.'),
    (12, 'Cryptographic hashing is used to secure data integrity on the blockchain, with SHA-256 being widely used in Bitcoin.'),
    (13, 'The 51% attack is a security vulnerability in which an entity controls the majority of the networks mining power, potentially compromising the integrity of the blockchain.'),
    (14, 'Scalability is a significant challenge for blockchain networks, and solutions include layer-2 scaling (e.g., Lightning Network for Bitcoin) and alternative consensus algorithms.'),
    (15, 'Interoperability standards like the Interledger Protocol (ILP) aim to facilitate communication between different blockchain networks.'),
    (16, 'Cryptocurrency wallets store private keys used to access and manage a users digital assets.'),
    (17, 'Hardware wallets, like Ledger and Trezor, provide enhanced security by keeping private keys offline.'),
    (18, 'DeFi refers to financial services built on blockchain technologies, providing decentralized alternatives to traditional banking services.'),
    (19, 'Yield farming is a DeFi practice where users can earn rewards by lending or staking their crypto assets.'),
    (21, 'NFTs represent unique digital or physical items on the blockchain, often used for digital art, collectibles, and gaming assets.'),
    (22, 'Ethereums ERC-721 standard is widely adopted for creating NFTs.'),
    (23, 'Centralized exchanges (CEX) like Binance and Coinbase facilitate the trading of cryptocurrencies'),
    (24, 'Decentralized exchanges (DEX) operate without a central authority, allowing users to trade directly from their wallets.'),
    (25, 'Mining involves solving complex mathematical problems to add blocks to the blockchain, a process used in Proof of Work consensus.'),
    (26, 'Bitcoins mining difficulty adjusts approximately every two weeks to maintain a consistent block creation time'),
    (27, 'Proof of Stake (PoS) is an alternative to PoW, where validators are chosen to create new blocks based on the amount of cryptocurrency they hold and are willing to "stake."'),
    (28, 'On-chain governance allows token holders to participate in decision-making processes for the development and evolution of a blockchain network.'),
    (29, 'ERC-20 is a widely adopted token standard on Ethereum, enabling the creation of fungible tokens.'),
    (30, 'Wrapped Bitcoin (WBTC) is an example of a tokenized representation of Bitcoin on the Ethereum blockchain.'),
    (31, 'Cross-chain protocols, like Polkadot and Cosmos, aim to connect different blockchains, enabling interoperability and collaboration.'),
    (32, 'The DAO (Decentralized Autonomous Organization) hack in 2016 led to the Ethereum hard fork, resulting in the creation of Ethereum (ETH) and Ethereum Classic (ETC).'),
    (33, 'Blockchain is utilized in supply chain management to enhance transparency and traceability, reducing the risk of counterfeit goods.'),
    (34, 'Quantum computers pose a potential threat to traditional cryptographic algorithms, leading to the development of quantum-resistant cryptographic methods.'),
    (35, 'Ethereum 2.0 aims to transition from PoW to PoS and improve scalability through the introduction of shard chains.'),
    (36, 'Monero (XMR) and Zcash (ZEC) are examples of privacy-focused cryptocurrencies that use advanced cryptographic techniques to anonymize transactions.'),
    (37, 'DAOs are organizations run by smart contracts and code, enabling decentralized decision-making and resource allocation.'),
    (38, 'Cryptocurrency regulations vary globally, with some countries embracing the technology, while others impose strict regulations or outright bans.'),
    (39, 'Web3.js is a popular JavaScript library for interacting with Ethereum smart contracts, facilitating the development of decentralized applications.'),
    (40, 'Truffle is a development framework for Ethereum that provides tools for smart contract compilation, testing, and deployment.'),
    (41, 'Cosmos SDK enables developers to build custom blockchains that can communicate with other blockchains through the Inter-Blockchain Communication (IBC) protocol'),
    (42, 'Substrate, developed by Parity Technologies, is a framework for building blockchains that supports custom consensus algorithms.'),
    (43, 'Oracles are third-party services that provide external data to smart contracts, allowing them to interact with real-world information.'),
    (44, 'Chainlink (LINK) is a decentralized oracle network that facilitates secure data feeds for smart contracts.'),
    (45, 'Self-sovereign identity (SSI) on the blockchain allows individuals to have control over their own identity information, enhancing privacy and security.'),
    (46, 'Blockchain is used in healthcare to secure and streamline the sharing of patient data, ensuring data integrity and interoperability.'),
    (47, 'Governance tokens, like COMP (Compound) and MKR (Maker), enable holders to participate in the decision-making processes of decentralized protocols.'),
    (48, 'Stablecoins, such as USDC and DAI, aim to maintain a stable value by pegging their price to a reserve asset like the US Dollar.'),
    (49, 'The term "immutability" in blockchain refers to the inability to alter historical data once its been added to the blockchain.'),
    (50, 'Some projects implement token burn mechanisms, where a portion of the tokens is intentionally destroyed, reducing the total supply and potentially increasing scarcity.'),
    (51, 'Blockchain-based voting systems aim to enhance the security, transparency, and integrity of election processes.'),
    (52, 'Blockchain networks like Filecoin and IPFS leverage decentralized storage solutions, allowing users to contribute storage space and earn tokens.'),
    (53, 'Optimistic Rollups and zk-Rollups are Layer-2 scaling solutions that aim to increase transaction throughput on Ethereum by processing transactions off-chain.'),
    (54, 'DEX aggregators, such as 1inch and Kyber Network, optimize trades by splitting them across multiple decentralized exchanges to achieve the best rates.'),
    (55, 'Smart contract audits are crucial for identifying vulnerabilities and ensuring the security of code before it is deployed on the blockchain.'),
    (56, 'Tokenomics refers to the economic model of a cryptocurrency, including factors like token supply, distribution, and utility within the ecosystem.'),
    (57, 'Blockchain gaming involves using blockchain technology for in-game assets, ownership, and verifiable scarcity, as seen in games like Axie Infinity and CryptoKitties.'),
    (58, 'Gas fees on blockchain networks represent the cost of computational resources required to process and validate transactions.'),
    (59, 'Blockchain is explored for social impact initiatives, such as transparent charity donations, supply chain traceability for fair trade products, and identity solutions for refugees.'),
    (60, 'Metrics like node distribution, hash power distribution, and governance participation are used to quantify the degree of decentralization in a blockchain network.'),
    (61, 'Mimblewimble-based cryptocurrencies like Grin and Beam focus on privacy by using confidential transactions and scalable blockchain design.'),
    (62, 'The "Flash Loan" attack is a type of exploit where an attacker borrows a large sum of money within a single transaction to manipulate markets or exploit vulnerabilities.'),
    (63, 'Multisig wallets require multiple private keys to authorize a transaction, enhancing security and reducing the risk of single points of failure.'),
    (64, 'Permissioned blockchains, often used in enterprise settings, rely on a predefined group of nodes to reach consensus, providing more control over network participants.'),
    (65, 'Blockchain is explored for creating and managing legally binding contracts, reducing the need for intermediaries and enhancing transparency.'),
    (66, 'Token locking and vesting mechanisms are implemented to prevent immediate selling by early investors and team members, promoting long-term commitment.'),
    (67, 'Blockchain can be utilized to timestamp and verify the authenticity of intellectual property, such as patents, trademarks, and digital content.'),
    (68, 'Wanchain and Aion are blockchain projects focused on interoperability, allowing different blockchain networks to communicate with each other.'),
    (69, 'Solana and Avalanche are examples of Layer-1 blockchains designed for high throughput and low transaction fees.'),
    (70, 'DAOs often manage a treasury of funds, and decentralized autonomous organizations use governance tokens to vote on proposals for fund allocation.'),
    (71, 'Blockchain is explored for its potential to revolutionize the music industry by providing transparent royalty distribution and preventing copyright infringement.'),
    (72, 'Atomic swaps enable the direct exchange of different cryptocurrencies without the need for an intermediary, enhancing decentralized trading.'),
    (73, 'Payment channels, like the Lightning Network for Bitcoin, enable off-chain transactions, reducing the load on the main blockchain for microtransactions.'),
    (74, 'Binance Smart Chain and Cardano are platforms that support smart contracts, providing alternatives to Ethereum for decentralized application development.'),
    (75, 'Blockchain is explored in the energy sector for efficient energy trading, grid management, and transparent tracking of renewable energy sources.'),
    (76, 'Enjin and Flow are blockchain platforms that focus on non-fungible tokens (NFTs) for gaming and digital collectibles.'),
    (77, 'ERC-1155 is a token standard on Ethereum that allows the creation of both fungible and non-fungible tokens within a single contract.'),
    (78, 'Upgradeable smart contracts use mechanisms like proxies and modular code design to facilitate updates without disrupting existing applications.'),
    (79, 'Blockchain enhances transparency and traceability in logistics by providing a tamper-proof record of the movement and status of goods.'),
    (80, 'Decentralized exchanges like Uniswap use liquidity pools where users can contribute their crypto assets to facilitate trading and earn fees.'),
    (81, 'The integration of blockchain and AR can be seen in projects aiming to tokenize virtual assets and create immersive experiences.'),
    (82, 'DAOs are used to fund cultural projects, allowing communities to collectively decide on the allocation of funds for art, music, and creative endeavors.'),
    (83, 'Blockchain can help protect intellectual property rights by providing a transparent and unalterable record of ownership and licensing agreements.'),
    (84, 'Flash loans in decentralized finance (DeFi) allow users to borrow assets without collateral, but the borrowed funds must be repaid within a single transaction block.'),
    (85, 'Optimistic Ethereum and zkSync are Layer-2 scaling solutions designed to alleviate congestion on the Ethereum network and reduce gas fees.'),
    (86, 'Cryptoeconomic models leverage game theory to incentivize desirable behavior within decentralized networks, such as staking and governance participation.'),
    (87, 'Blockchain-based smart contracts are explored in the insurance industry for automating claims processing and improving transparency.'),
    (88, 'Beam and Grin are privacy-focused cryptocurrencies based on the Mimblewimble protocol, aiming to enhance transaction privacy.'),
    (89, 'The United Nations explores blockchain technology for humanitarian efforts, including transparent aid distribution and identity verification for refugees.'),
    (90, 'Decentralized identity solutions, such as Microsofts Ion and the Decentralized Identity Foundation (DIF), aim to provide secure and interoperable identity across platforms.'),
    (91, 'NFT smart contracts can automatically enforce royalties for creators, ensuring they receive a percentage of sales whenever their NFTs are traded.'),
    (92, 'Blockchain is applied in agriculture for supply chain traceability, quality assurance, and efficient management of agricultural data.'),
    (93, 'Blockchain technology is utilized in charitable initiatives to ensure transparency in donations and track the impact of funds in real-time.'),
    (94, 'Immutable X is a Layer-2 scaling solution on Ethereum specifically designed for NFTs, offering instant trade confirmation and zero gas fees.'),
    (95, 'Decentralized Identity (DID) standards, such as W3Cs Verifiable Credentials, enable users to have portable, self-owned digital identities.'),
    (96, 'Front-running is a concern in decentralized exchanges where traders use privileged information to manipulate transactions before they are executed.'),
    (97, 'Gas tokens like CHI and GST2 allow users to pre-purchase gas at lower prices during periods of low network activity, potentially saving on transaction costs.'),
    (98, 'Synthetix uses a system of over-collateralization to issue synthetic assets, enabling users to trade on-chain representations of real-world assets.'),
    (99, 'Web3 wallet standards like WalletConnect enable users to connect their wallets to decentralized applications across different devices and browsers.'),
    (100, 'Blockchain is explored in education for secure credentialing, transparent certification processes, and the validation of academic achievements.'),
    (101, 'Gas tokenomics involve economic models that determine the pricing and allocation of gas on blockchain networks.'),
    (102, 'DAOstack is a platform for building DAOs that can interact and collaborate with each other, creating a network of decentralized organizations.'),
    (103, 'Luxury brands use blockchain to verify the authenticity of high-end goods, reducing the prevalence of counterfeit products.'),
    (104, 'Platforms like Aave and Compound enable users to earn interest on their crypto assets through decentralized lending and borrowing.'),
    (105, 'Blockchain is applied in sports for ticketing, authenticating memorabilia, and creating verifiable records of athlete performance.'),
    (106, 'Rarible and OpenSea are popular NFT marketplaces where users can create, buy, and sell non-fungible tokens.'),
    (107, 'Blockchain is used to create transparent and tradable renewable energy credits, ensuring accurate tracking of green energy production.'),
    (108, 'Polygon (formerly Matic) and Arbitrum are Layer-2 solutions that provide bridges connecting Ethereum with other blockchains.'),
    (109, 'Smart contracts are explored in real estate for executing property transactions, handling rental agreements, and managing property records.'),
    (110, 'Blockchain enhances security in telecommunications by providing a tamper-resistant ledger for mobile number portability and identity verification.'),
    (111, 'Tokenized governance mechanisms allow token holders to propose and vote on changes to the protocol, influencing the development and direction of a project.'),
    (112, 'Some NFT smart contracts allow creators to receive royalties every time the NFT changes hands, ensuring ongoing compensation for their work.'),
    (113, 'Projects like Steem and Hive leverage blockchain to create decentralized social media platforms, where users can earn rewards for content creation.'),
    (114, 'Interledger Protocol (ILP) and Polkadots Substrate framework facilitate interoperability by allowing smart contracts to operate seamlessly across different blockchains.'),
    (115, 'Projects like Arweave and Filecoin offer decentralized storage solutions, where users can store and retrieve data on a distributed network.'),
    (116, 'Post-quantum cryptography standards, like NISTs ongoing project, aim to develop cryptographic algorithms resistant to quantum attacks'),
    (117, 'Blockchain enables the creation of virtual economies in games, where in-game assets can be owned, traded, and used across multiple gaming platforms.'),
    (118, 'ERC-777 is an improved token standard on Ethereum that adds advanced features like hooks and operator approvals for increased flexibility.'),
    (119, 'Self-sovereign identity platforms, such as Sovrin and uPort, use blockchain to enable users to control and share their identity information securely.'),
    (120, 'Wrapped tokens like Wrapped BTC (WBTC) and Wrapped ETH (WETH) enable the representation of assets from one blockchain on another through cross-chain bridges'),
    (121, 'ERC-1155, developed by Enjin, allows for the creation of both fungible and non-fungible tokens within a single smart contract.'),
    (122, 'Blockchain is explored in the aviation industry for secure and transparent record-keeping of aircraft maintenance, flight data, and supply chain management.'),
    (123, 'Real-world assets, such as real estate and precious metals, can be tokenized on the blockchain, providing fractional ownership and liquidity.'),
    (124, 'Projects like the Decentralized Identity Foundation (DIF) aim to establish standards for interoperable decentralized identity across various platforms.'),
    (125, 'Quantum-resistant cryptographic algorithms, like lattice-based cryptography, are being explored to secure blockchain networks against potential quantum threats'),
    (126, 'Some Layer-2 solutions, like Optimistic Ethereum, implement governance mechanisms to involve the community in decision-making processes.'),
    (127, 'EIP-1559 is a major upgrade proposal for Ethereum that aims to improve transaction fee mechanisms and enhance user experience'),
    (128, 'Blockchain is applied in digital advertising for transparent and fraud-resistant tracking of ad impressions, clicks, and payments'),
    (129, 'Liquid Democracy combines elements of direct and representative democracy, allowing users to vote directly or delegate their voting power within a DAO.'),
    (130, 'Automated Market Makers (AMMs), like Uniswap and SushiSwap, facilitate decentralized token swaps without the need for traditional order books.'),
    (131, 'Vyper is an alternative programming language for Ethereum smart contracts, designed for simplicity and security.'),
    (132, 'In-game assets and currencies on blockchain-based games can be traded on external markets, creating decentralized gaming economies.'),
    (133, 'The Lightning Network is a Layer-2 scaling solution for Bitcoin, enabling fast and low-cost transactions through off-chain payment channels.'),
    (134, 'Some projects allow users to stake their NFTs in liquidity pools, earning additional tokens as rewards.'),
    (135, 'Blockchain is explored for carbon credit trading and tracking renewable energy production to contribute to sustainability efforts.'),
    (136, 'Platforms like Audius leverage blockchain to allow artists to monetize their music directly through token rewards and streaming payments.'),
    (137, 'Move is a programming language for the Libra blockchain (now Diem) developed by Facebook, designed for creating smart contracts.'),
    (138, 'Governments are exploring blockchain for identity management, public records, and transparent governance processes.'),
    (139, 'Token bridges, like the xDai Bridge, facilitate cross-platform transactions by bridging tokens between different blockchain networks.'),
    (140, 'Blockchain is applied to enhance the efficiency and transparency of cross-border payments, reducing delays and costs.'),
    (141, 'Smart contracts are utilized for escrow services, automating the release of funds when predefined conditions are met.'),
    (142, 'Blockchain is explored in healthcare for secure and transparent management of genetic data, ensuring privacy and data integrity.'),
    (143, 'DAOs are used in the art world to collectively invest in and govern art collections, enabling decentralized decision-making by a community of art enthusiasts.'),
    (144, 'Filecoin is a decentralized storage network that allows users to buy and sell unused storage space, creating a global, distributed file storage system.'),
    (145, 'TCRs use blockchain to create decentralized lists or registries where token holders curate and vote on the inclusion or removal of items based on predefined criteria.'),
    (146, 'Bridges like the Wormhole bridge enable the movement of digital assets across different blockchain networks, connecting ecosystems and expanding liquidity.'),
    (147, 'Blockchain is explored in the video streaming industry to provide transparent revenue distribution, combat piracy, and enhance content delivery.'),
    (148, 'Smart contracts in supply chain finance automate payment processes based on predefined conditions, facilitating quicker and more efficient transactions.'),
    (149, 'zkPorter is a Layer-2 scaling solution that combines zk-Rollups and Validium to enhance the scalability of blockchain networks.'),
    (150, 'Proof of Reserve on the blockchain provides transparent verification of the reserve assets backing a cryptocurrency, enhancing trust and accountability.'),
    (151, 'Connext and Raiden are examples of layer-2 solutions that facilitate off-chain token transfers, improving scalability and reducing transaction fees.'),
    (152, 'Some blockchain-based games aim to create multiverses where in-game assets and characters can be used across different gaming environments'),
    (153, 'Blockchain is explored for secure and verifiable storage of COVID-19 test results and vaccination records to streamline travel and access to public spaces.'),
    (154, 'Stablecoins pegged to commodities like gold, such as PAX Gold (PAXG), provide a digital representation of physical assets, offering stability and liquidity.'),
    (155, 'Blockchain technology is applied in online notarization services, ensuring the authenticity and integrity of notarized documents.'),
    (156, 'Some NFT marketplaces explore fractional ownership models, allowing multiple users to collectively own and trade portions of high-value NFTs.'),
    (157, 'Smart contracts can be used in event ticketing to automate ticket issuance, resale, and revenue distribution, reducing fraud and scalping'),
    (158, 'Blockchain facilitates transparent and efficient carbon offset marketplaces, where individuals and companies can trade carbon credits.'),
    (159, 'DeFi aggregators like Yearn Finance and Zapper allow users to optimize their yield farming strategies by interacting with multiple protocols.'),
    (160, 'NEP-11 on the NEO blockchain and BEP-721 on Binance Smart Chain are examples of token standards similar to ERC-721 for non-fungible tokens.'),
    (161, 'Web3 governance models aim to create decentralized decision-making processes for managing protocols, platforms, and ecosystems.'),
    (162, 'Atomic swaps can extend beyond simple token exchanges to enable the trustless exchange of different blockchain-based assets.'),
    (163, 'Blockchain-based smart contracts are explored in legal practice for executing and enforcing legal agreements, automating contract execution.'),
    (164, 'NFTs can represent intellectual property licenses, allowing creators to grant permission for specific use cases while retaining ownership rights.'),
    (165, 'Dynamic NFTs can change over time based on external factors or user interactions, adding programmable functionality to non-fungible tokens.'),
    (166, 'Platforms like Thorchain enable cross-platform token swaps by connecting different blockchain networks and liquidity pools.'),
    (167, 'Blockchain is explored in e-governance initiatives to enhance transparency, reduce corruption, and streamline public service processes.'),
    (168, 'Blockchain ensures secure and interoperable management of healthcare data, enabling patients to control access to their medical records.'),
    (169, 'TRC-721 on the TRON blockchain and HRC-721 on the Harmony blockchain are examples of token standards similar to ERC-721 for non-fungible tokens.'),
    (170, 'Some DeFi platforms accept NFTs as collateral for loans, allowing users to leverage their non-fungible assets to access liquidity.'),
    (171, 'Blockchain can facilitate circular economy initiatives by tracking the lifecycle of products, enabling efficient recycling and reducing waste.'),
    (172, 'Chainlink provides decentralized oracle networks that connect smart contracts with real-world data, serving multiple blockchain platforms.'),
    (173, 'The integration of decentralized identity solutions in DeFi enhances user privacy and security while interacting with financial protocols.'),
    (174, 'DAOs are explored in the film industry to enable decentralized funding, decision-making, and profit-sharing for independent film projects.'),
    (175, 'Blockchain empowers individuals to own and control their personal data, allowing them to selectively share information with service providers.'),
    (176, 'Smart contracts automate subscription services, ensuring timely payments and access to digital content while reducing friction in billing processes.'),
    (177, 'Cross-Platform tools like the EVM-compatible Moonbeam facilitate the deployment of Ethereum smart contracts on other blockchain networks.'),
    (178, 'NFTs can represent virtual real estate, assets, and experiences in VR worlds, creating new possibilities for ownership and monetization.'),
    (179, 'Blockchain enhances the authenticity and traceability of 3D-printed products by recording their design and production history.'),
    (180, 'Governance tokens like COMP and CRV are designed to influence decision-making on specific DeFi platforms and can be used across various ecosystems.'),
    (181, 'Blockchain-based platforms like Theta utilize decentralized networks to improve content delivery for video streaming, reducing latency and costs.'),
    (182, 'Terras stablecoin (UST) operates across multiple blockchain networks, providing stability and liquidity for users in various ecosystems.'),
    (183, 'Web3 technologies, including blockchain, contribute to the development of secure and transparent autonomous vehicle systems.'),
    (184, 'Blockchain facilitates peer-to-peer trading of renewable energy, allowing users to buy and sell excess energy directly within a decentralized network'),
    (185, 'Lending protocols like Aave and Compound offer cross-platform compatibility, allowing users to borrow and lend assets across different blockchains.'),
    (186, 'Blockchain-based insurance platforms automate claims processing and improve transparency, reducing fraud in the insurance industry.'),
    (187, 'Smart contracts automate auction processes, enabling transparent and secure bidding for digital and physical assets.'),
    (188, 'Oracles, such as Band Protocol, provide cross-platform solutions to fetch external data for smart contracts on multiple blockchain networks.'),
    (189, 'Digital identity verification on the blockchain enhances online security and streamlines user authentication processes.'),
    (190, 'DAOs use token-based governance models to enable community members to participate in decision-making processes and influence project development.'),
    (191, 'Blockchain-based smart contracts are used to tokenize real estate assets, allowing for fractional ownership and simplified property transactions.'),
    (192, 'Automated Market Makers (AMMs), common in decentralized exchanges like Uniswap and PancakeSwap, use liquidity pools for decentralized trading.'),
    (193, 'Connext, Hop Protocol, and Wormhole provide solutions for cross-platform token bridges, enabling assets to move seamlessly across different blockchains.'),
    (194, 'Web3 authentication standards like OAuth and OpenID Connect enable users to log in seamlessly across various platforms using their blockchain identity.'),
    (195, 'NFTs extend to virtual fashion, allowing users to buy, sell, and showcase unique digital clothing items in virtual worlds and metaverse environments.'),
    (196, 'Blockchain addresses challenges in music royalties by providing transparent and automated payment systems, ensuring fair compensation for artists.'),
    (197, 'Interledger Protocol (ILP) and Polkadots XCMP (Cross-Chain Message Passing) aim to enhance interoperability by facilitating communication between blockchains.'),
    (198, 'Token burn mechanisms in smart contracts involve destroying a portion of tokens, contributing to deflationary models and potential value appreciation.'),
    (199, 'Platforms like Terra and Mirror Protocol facilitate stablecoin swaps across different blockchain networks, providing stability and liquidity.'),
    (200, 'Blockchain enhances security and transparency in virtual events by providing tamper-resistant records of attendee interactions, ticketing, and rewards.');
    (201, 'Decentralized Identity (DID) solutions, such as Sovrin and Civic, leverage blockchain for secure and privacy-enhanced digital identity verification.'),
    (202, 'DAOs are used in content curation platforms, where community members collectively curate and vote on valuable content, influencing rankings and rewards. Cross-Platform Layer-2 Solutions:'),
    (203, 'Layer-2 solutions like Optimistic Rollups and zk-Rollups aim to scale blockchain networks by processing transactions off-chain while ensuring security.'),

-- Verify the data
SELECT * FROM facts;
